create table books (
	book_id int generated by default as identity primary key,
	title varchar(50) not null,
	author varchar(50) not null,
	published_year int not null,
	genre varchar(20) not null
);

insert into books(title, author, published_year, genre) values('Congreso de Futurologia', 'Stanislaw Lem', 1978, 'Ciencia Ficcion');
insert into books(title, author, published_year, genre) values('Un Mundo Feliz', 'H. G. Wells', 1975, 'Ciencia Ficcion');
insert into books(title, author, published_year, genre) values('La Isla del Tesoro', 'Robert Lewis Stevenson', 1948, 'Aventuras');
insert into books(title, author, published_year, genre) values('El Señor de los Anillos', 'J. R. Tolkien', 1945, 'Fantasia');