/*
 * JaspertReports JSF Plugin Copyright (C) 2011 A. Alonso Dominguez
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version. This library is distributed in the hope
 * that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU Lesser General Public License for more details. You should have
 * received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place, Suite 330, Boston, MA 02111-1307 USA A.
 *
 * Alonso Dominguez
 * alonsoft@users.sf.net
 */
package net.sf.jasperreports.jsf.engine;

import java.io.IOException;
import java.io.OutputStream;

import javax.faces.context.FacesContext;

import net.sf.jasperreports.jsf.component.UIReport;

/**
 * The Exporter interface.
 *
 * @author A. Alonso Dominguez
 */
public interface Exporter {

    /**
     * Content type of the output generated by this exporter.
     *
     * @return the exporter's content type.
     */
    public abstract String getContentType();

    /**
     * Export.
     *
     * @param context the context
     * @param component the report component
     * @param stream the stream
     *
     * @throws IOException Signals that an I/O exception has occurred.
     * @throws ExporterException the exporter exception
     */
    public void export(final FacesContext context,
            final UIReport component, final OutputStream stream)
            throws IOException, ExporterException;

}
